import Link from "next/link";
import { ArrowRight, Box, Check, FileCheck2, Info, MessageCircle, PackageCheck, Plane, Ship, Truck, Warehouse } from "lucide-react";
import { company, whatsappLink } from "@/config/company";
import type { ContentPage } from "@/data/pages";
import type { Service } from "@/data/services";
import { getServices } from "@/data/services";
import { faqGroups } from "@/data/site";
import type { Locale } from "@/i18n/config";
import { localizePath } from "@/i18n/config";
import { getUi } from "@/i18n/dictionaries";
import { FAQAccordion } from "./faq-accordion";
import { ContactForm, QuoteForm, TrackingForm } from "./forms";
import { Gallery } from "./gallery";
import { Breadcrumbs, CargoNotice, ContactStrip, JsonLd, OfficeGrid, PageHero, QuoteCTA, ServiceCard, TickList } from "./ui";

export function ServicesOverview({locale}:{locale:Locale}){
  const t=getUi(locale);const services=getServices(locale);const sw=locale==="sw";
  return <><Breadcrumbs locale={locale} items={[{label:t.nav.services}]}/><PageHero locale={locale} eyebrow={sw?"Njia inayofaa kwa mzigo wako":"The right method for your cargo"} title={sw?"Huduma za mizigo zilizopangwa kwa mahitaji halisi":"Cargo services planned around real shipping needs"} description={sw?"Mzigo tofauti unahitaji njia tofauti. Linganisha chaguo, kisha tutakagua uzito, ujazo, uharaka, nyaraka na mwisho.":"Different cargo calls for different transport and handling. Compare the options, then let us assess weight, volume, urgency, documents and destination."} image="/images/services.webp" alt={sw?"Shughuli za mizigo katika mtandao wa usafirishaji":"Cargo operations across an international logistics network"}><Link className="button button-primary" href={localizePath(locale,"request-quote")}>{t.actions.quote}</Link></PageHero>
    <section className="section"><div className="container"><div className="section-heading split"><div><span className="eyebrow">{t.nav.services}</span><h2>{sw?"Chagua mahali pa kuanzia":"Find the right starting point"}</h2></div><p>{sw?"Kila huduma hapa inaeleza mizigo inayofaa, faida, mchakato, nyaraka na vidokezo. Bei na muda huthibitishwa baada ya ukaguzi.":"Every service explains suitable cargo, benefits, process, information and preparation. Rates and timing are confirmed after review."}</p></div><div className="service-grid">{services.map(s=><ServiceCard key={s.slug} locale={locale} service={s}/>)}</div></div></section>
    <section className="section comparison-section"><div className="container"><div className="section-heading"><span className="eyebrow">{sw?"Ulinganisho":"Comparison"}</span><h2>{sw?"Njia kuu zina tofauti gani?":"How the main options differ"}</h2></div><div className="comparison-table" role="region" aria-label={sw?"Ulinganisho wa huduma":"Service comparison"} tabIndex={0}><table><thead><tr><th>{sw?"Chaguo":"Option"}</th><th>{sw?"Inafaa kwa":"Useful for"}</th><th>{sw?"Jambo kuu":"Planning focus"}</th></tr></thead><tbody><tr><th><Plane/> {services[0].title}</th><td>{sw?"Mizigo midogo, ya haraka au thamani kubwa":"Smaller, urgent or higher-value cargo"}</td><td>{sw?"Kukubalika kwa ndege, vipimo na nyaraka":"Airline acceptance, dimensions and documents"}</td></tr><tr><th><Ship/> {services[1].title}</th><td>{sw?"Mizigo mikubwa, samani, mashine na stock":"Bulk loads, furniture, machinery and stock"}</td><td>{sw?"Ujazo, ufungashaji na ratiba ya meli":"Volume, packing and sailing schedule"}</td></tr><tr><th><Truck/> {services[2].title}</th><td>{sw?"Wanaohitaji ukusanyaji na uwasilishaji":"Collection and delivery coordination"}</td><td>{sw?"Anwani, upatikanaji na mipaka ya huduma":"Address, access and confirmed service scope"}</td></tr><tr><th><Warehouse/> {services[4].title}</th><td>{sw?"Wasambazaji wengi au vifurushi kadhaa":"Multiple suppliers or packages"}</td><td>{sw?"Rejea, utambulisho, vipimo na muda":"References, identification, measurement and timing"}</td></tr></tbody></table></div><p className="confirmation-note"><Info/>{sw?"Hakuna muda maalumu au bei ya kudumu iliyochapishwa. Timu itathibitisha baada ya kukagua mzigo.":"No fixed transit time or price is published. The team confirms current options after reviewing the cargo."}</p></div></section><div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div></>;
}

export function ServiceDetail({locale,service}:{locale:Locale;service:Service}){
  const t=getUi(locale);const services=getServices(locale);const related=service.related.map(slug=>services.find(s=>s.slug===slug)).filter(Boolean) as Service[];
  const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:service.faqs.map(item=>({"@type":"Question",name:item.q,acceptedAnswer:{"@type":"Answer",text:item.a}}))};
  return <><JsonLd data={faqSchema}/><Breadcrumbs locale={locale} items={[{label:t.nav.services,href:localizePath(locale,"services")},{label:service.title}]}/><PageHero locale={locale} eyebrow="TCAST CARGO" title={service.title} description={service.short} image={service.image} alt={service.alt}><Link className="button button-primary" href={localizePath(locale,"request-quote")}>{t.actions.quote}</Link><a className="button button-outline-light" href={whatsappLink()} target="_blank" rel="noreferrer"><MessageCircle/>{t.actions.whatsapp}</a></PageHero>
    <section className="section service-intro"><div className="container narrow-copy"><span className="eyebrow">{service.title}</span><h2>{locale==="en"?"Service overview":"Muhtasari wa huduma"}</h2>{service.overview.map(p=><p key={p}>{p}</p>)}<CargoNotice locale={locale}/></div></section>
    <section className="section detail-panels"><div className="container three-panels"><article><span><PackageCheck/></span><h2>{t.labels.suitable}</h2><TickList items={service.suitable}/></article><article><span><Box/></span><h2>{t.labels.cargoTypes}</h2><TickList items={service.cargo}/></article><article><span><Check/></span><h2>{t.labels.benefits}</h2><TickList items={service.benefits}/></article></div></section>
    <section className="section service-process"><div className="container"><div className="section-heading centered"><span className="eyebrow">{t.labels.process}</span><h2>{locale==="en"?`How ${service.title.toLowerCase()} is coordinated`:`Jinsi ${service.title.toLowerCase()} inavyoratibiwa`}</h2></div><ol className="detail-process">{service.process.map((step,index)=><li key={step}><span>{index+1}</span><p>{step}</p></li>)}</ol></div></section>
    <section className="section info-columns"><div className="container two-columns"><article><span className="panel-icon"><FileCheck2/></span><h2>{t.labels.documents}</h2><TickList items={service.documents}/></article><article><span className="panel-icon"><PackageCheck/></span><h2>{t.labels.tips}</h2><TickList items={service.tips}/></article></div></section>
    <section className="section faq-preview"><div className="container faq-preview-grid"><div><span className="eyebrow">FAQ</span><h2>{t.labels.questions}</h2><p>{locale==="en"?"These answers are service-specific. Contact TCAST before sending regulated or unusual cargo.":"Majibu haya yanahusu huduma hii. Wasiliana na TCAST kabla ya kutuma mzigo maalumu au uliodhibitiwa."}</p><Link className="button button-outline" href={localizePath(locale,"faq")}>{t.actions.viewAll}<ArrowRight/></Link></div><FAQAccordion items={service.faqs}/></div></section>
    <section className="section related-services"><div className="container"><div className="section-heading"><span className="eyebrow">{t.labels.related}</span><h2>{locale==="en"?"Build the right cargo plan":"Kamilisha mpango sahihi wa mzigo"}</h2></div><div className="service-grid compact">{related.map(s=><ServiceCard key={s.slug} locale={locale} service={s}/>)}</div></div></section><div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div></>;
}

export function GeneralContentPage({locale,page}:{locale:Locale;page:ContentPage}){
  const t=getUi(locale);const isAbout=page.slug==="about";const isHow=page.slug==="how-it-works";const isLegal=page.slug.includes("policy")||page.slug.includes("terms");
  return <><Breadcrumbs locale={locale} items={[{label:page.title}]}/><PageHero locale={locale} eyebrow={page.eyebrow} title={page.title} description={page.description} image={page.image} alt={page.alt}>{!isLegal&&<Link className="button button-primary" href={localizePath(locale,"request-quote")}>{t.actions.quote}</Link>}</PageHero><section className={`section prose-page ${isHow?"timeline-page":""}`}><div className="container prose-layout"><aside><span>{page.eyebrow}</span><p>{page.description}</p>{!isLegal&&<Link className="text-link" href={localizePath(locale,"contact")}>{t.actions.contact}<ArrowRight/></Link>}</aside><div className="prose-sections">{page.sections.map((section,index)=><section key={section.title}><span className="section-number">{String(index+1).padStart(2,"0")}</span><div><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<TickList items={section.bullets}/>}</div></section>)}</div></div></section>{isAbout&&<section className="section offices-section"><div className="container"><div className="section-heading centered"><span className="eyebrow">{t.nav.contact}</span><h2>{locale==="en"?"Our offices":"Ofisi zetu"}</h2></div><OfficeGrid locale={locale}/></div></section>}{isLegal?<div className="container contact-strip-wrap"><ContactStrip locale={locale}/></div>:<div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div>}</>;
}

export function TrackingPage({locale}:{locale:Locale}){const t=getUi(locale);const sw=locale==="sw";return <><Breadcrumbs locale={locale} items={[{label:t.nav.track}]}/><PageHero locale={locale} eyebrow={sw?"Sasisho la mzigo":"Shipment updates"} title={sw?"Fuatilia mzigo wako":"Track your shipment"} description={sw?"Weka rejea ya TCAST ili kupata taarifa ya mwisho inayopatikana. Hakuna rekodi za mfano zinazoonyeshwa.":"Enter your TCAST reference to request the latest available update. No sample shipment records are shown."} image="/images/tracking.webp" alt={sw?"Mfumo wa ufuatiliaji wa mizigo":"Cargo shipment tracking and logistics monitoring"}/><section className="section tracking-section"><div className="container tracking-layout"><TrackingForm locale={locale}/><aside className="tracking-help"><h2>{sw?"Unahitaji msaada?":"Need help with a reference?"}</h2><p>{sw?"Ikiwa mfumo haujaunganishwa au namba haipatikani, wasiliana na TCAST ukitaja mtumaji, mpokeaji na maelezo ya mzigo.":"If online tracking is not connected or your number is not found, contact TCAST with the sender, receiver and cargo details."}</p><a className="button button-primary" href={whatsappLink()} target="_blank" rel="noreferrer"><MessageCircle/>{t.actions.whatsapp}</a><a className="button button-outline" href={`tel:${company.phones.tanzania.href}`}>{company.phones.tanzania.display}</a><a className="button button-outline" href={`tel:${company.phones.tanzaniaSecondary.href}`}>{company.phones.tanzaniaSecondary.display}</a></aside></div></section></>}

export function QuotePage({locale}:{locale:Locale}){const t=getUi(locale);const sw=locale==="sw";return <><Breadcrumbs locale={locale} items={[{label:t.nav.quote}]}/><PageHero locale={locale} eyebrow={sw?"Tuanze na taarifa sahihi":"Start with the right information"} title={sw?"Omba makadirio ya mzigo":"Request a cargo quote"} description={sw?"Tuma taarifa za mzigo kwa ukaguzi wa anga, bahari, kuunganisha au mlango hadi mlango.":"Send the cargo details for review across air, sea, consolidation or door-to-door options."} image="/images/request-quote.webp" alt={sw?"Vifurushi vikipimwa kwa makadirio":"Cargo packages being measured for a freight estimate"}/><section className="section form-section"><div className="container form-layout"><QuoteForm locale={locale}/><aside className="form-aside"><h2>{sw?"Kabla ya kutuma":"Before you submit"}</h2><TickList items={sw?["Orodhesha kila aina ya bidhaa","Tumia uzito na vipimo vya karibu","Taja vitu dhaifu, betri na vimiminika","Pakia faili lisilozidi 5MB","Ombi litakaguliwa kabla ya kuthibitishwa"]:["List every type of item","Use realistic estimated weight and dimensions","Declare fragile goods, batteries and liquids","Attach a file no larger than 5MB","The request is reviewed before anything is confirmed"]}/><CargoNotice locale={locale}/><p className="privacy-hint">{sw?"Taarifa hutumika kukagua ombi lako.":"Your information is used to review the enquiry."} <Link href={localizePath(locale,"privacy-policy")}>{sw?"Soma Sera ya Faragha":"Read the Privacy Policy"}</Link>.</p></aside></div></section></>}

export function FAQPage({locale}:{locale:Locale}){const t=getUi(locale);const sw=locale==="sw";const all=faqGroups[locale].flatMap(g=>g.items);const schema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:all.map(i=>({"@type":"Question",name:i.q,acceptedAnswer:{"@type":"Answer",text:i.a}}))};return <><JsonLd data={schema}/><Breadcrumbs locale={locale} items={[{label:t.nav.faq}]}/><PageHero locale={locale} eyebrow={sw?"Mwongozo kabla ya kutuma":"Guidance before you ship"} title={sw?"Maswali yanayoulizwa mara kwa mara":"Frequently asked questions"} description={sw?"Majibu kuhusu usafiri, forodha, ufungashaji, ufuatiliaji na makadirio. Masharti yanaweza kubadilika; thibitisha mzigo wako na TCAST.":"Practical answers on freight, customs, packing, tracking and quotes. Requirements can change; confirm your exact cargo with TCAST."} image="/images/faq.webp" alt={sw?"Mteja akipokea mwongozo wa usafirishaji":"Customer receiving practical cargo guidance"}/><section className="section faq-page"><div className="container">{faqGroups[locale].map(group=><section className="faq-group" key={group.group}><div><span>FAQ</span><h2>{group.group}</h2></div><FAQAccordion items={group.items}/></section>)}</div></section><div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div></>}

export function GalleryPage({locale}:{locale:Locale}){const t=getUi(locale);const sw=locale==="sw";return <><Breadcrumbs locale={locale} items={[{label:t.nav.gallery}]}/><PageHero locale={locale} eyebrow={sw?"Picha za mfano":"Illustrative photography"} title={sw?"Mizigo, ufungashaji na usafirishaji":"Cargo, packing and freight operations"} description={sw?"Picha zilizo na leseni zinazoonyesha mazingira ya kawaida ya usafirishaji. Hazijawasilishwa kama shughuli halisi za TCAST.":"Licensed imagery showing typical logistics environments. These stock photographs are not presented as actual TCAST operations."} image="/images/gallery.webp" alt={sw?"Makontena na shughuli za bandari":"Cargo containers and port operations"}/><section className="section gallery-section"><div className="container"><Gallery locale={locale}/></div></section><div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div></>}

export function ContactPage({locale}:{locale:Locale}){const t=getUi(locale);const sw=locale==="sw";return <><Breadcrumbs locale={locale} items={[{label:t.nav.contact}]}/><PageHero locale={locale} eyebrow={sw?"Dubai na Dar es Salaam":"Dubai and Dar es Salaam"} title={sw?"Wasiliana na TCAST Cargo":"Contact TCAST Cargo"} description={sw?"Ongea na timu yetu kuhusu makadirio, kupokea mzigo, ufuatiliaji, forodha au uwasilishaji.":"Talk to our team about quotes, cargo receiving, tracking, customs or delivery coordination."} image="/images/contact.webp" alt={sw?"Mtaalamu wa usafirishaji akisaidia mteja":"Logistics support professional assisting a cargo customer"}><a className="button button-primary" href={whatsappLink()} target="_blank" rel="noreferrer"><MessageCircle/>{t.actions.whatsapp}</a></PageHero><section className="section offices-section"><div className="container"><div className="section-heading centered"><span className="eyebrow">{sw?"Tembelea au piga simu":"Visit or call"}</span><h2>{sw?"Ofisi zetu":"Our offices"}</h2><p>{sw?"Tumia anwani kamili zilizo hapa na uthibitishe saa za kufungua kabla ya kutembelea.":"Use the full addresses below and confirm current opening hours before visiting."}</p></div><OfficeGrid locale={locale} maps/></div></section><section className="section form-section contact-form-section"><div className="container form-layout"><ContactForm locale={locale}/><aside className="form-aside"><h2>{sw?"Njia za haraka":"Direct contact"}</h2><ContactStrip locale={locale}/><div className="faq-shortcut"><h3>{sw?"Una swali la kawaida?":"Have a common cargo question?"}</h3><p>{sw?"Angalia mwongozo wa ufungashaji, forodha, ufuatiliaji na bidhaa zilizodhibitiwa.":"See guidance on packing, customs, tracking and restricted goods."}</p><Link className="text-link" href={localizePath(locale,"faq")}>{t.nav.faq}<ArrowRight/></Link></div></aside></div></section><div className="container final-cta-wrap"><QuoteCTA locale={locale}/></div></>}
